path: '.'
path.n: NAMESPACE
path.d: DESCRIPTION
dir.r: R
dir.v: vignettes
dir.t: tests
extra.suggests:
- testthat
- pkgload
- rstudioapi
- rmarkdown
- knitr
pkg_ignore:
- testthat
- dummypackage
- rstudioapi
- knitr
- rmarkdown
- R6
document: yes
normalize: yes
inside_rmd: no
must.exist: yes
check_if_suggests_is_installed: yes
