# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# This workflow is created manually
# Please modify R-version when needed
on:
  push:
    branches: [main, master, centos-4.4]
  pull_request:
    branches: [main, master, centos]

name: R-CMD-check-centos

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    # See images on https://github.com/rstudio/r-docker
    # Test locally :
    # docker run -v /home/seb/fusen:/home/root/fusen -it rstudio/r-base:4.4-centos7 bash

    container: 'rstudio/r-base:4.4-centos7'

    name: r-base:4.4-centos7

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      REPO_NAME: "https://packagemanager.posit.co/cran/__linux__/centos7/latest"
      CRAN: "https://packagemanager.posit.co/cran/__linux__/centos7/latest"

    steps:
      # Keep checkout v3 for centos7 as C++ is not recent enough
      - uses: actions/checkout@v3

  #    - uses: r-lib/actions/setup-pandoc@v2

  
      - name: Install qpdf
        run: sudo yum -y install qpdf

      - name: Set RSPM in Rprofile
        run: |
          print(Sys.getenv("HOME"))
          print(getOption("repos"))
          cat('\noptions(repos = c(RSPM = "https://packagemanager.posit.co/cran/__linux__/centos7/latest", "https://cran.rstudio.com"))', file = file.path(Sys.getenv("HOME"), ".Rprofile"), append = TRUE)
          source(file.path(Sys.getenv("HOME"), ".Rprofile"))
          print(getOption("repos"))
        shell: Rscript {0}


      - name: Install deps
        run: |
          options(repos = c(RSPM = "https://packagemanager.posit.co/cran/__linux__/centos7/latest", "https://cran.rstudio.com"))
          install.packages("pak")
          pak::local_install_deps(dependencies = TRUE)
          pak::pkg_install("devtools")
        shell: Rscript {0}

      # checkout@v4 used here requires newer version for centos and C++
      #- uses: r-lib/actions/setup-r-dependencies@v2
      #  with:
      #    extra-packages: any::rcmdcheck
      #    needs: check

      # Avoid upload-artifact@v4 that requires newer C++
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: false

