# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, centos]
  pull_request:
    branches: [main, master, centos]

name: R-CMD-check-centos

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    container: 'rstudio/r-base:4.3-centos7'

    name: r-base:4.3-centos7

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      REPO_NAME: "https://packagemanager.posit.co/cran/__linux__/centos7/latest"
      CRAN: "https://packagemanager.posit.co/cran/__linux__/centos7/latest"

    steps:
      - uses: actions/checkout@v3

  #    - uses: r-lib/actions/setup-pandoc@v2
  
      - name: Install qpdf
        run: sudo yum -y install qpdf

      - name: Set RSPM in Rprofile
        run: |
          print(Sys.getenv("HOME"))
          print(getOption("repos"))
          cat('\noptions(repos = c(RSPM = "https://packagemanager.posit.co/cran/__linux__/centos7/latest", "https://cran.rstudio.com"))', file = file.path(Sys.getenv("HOME"), ".Rprofile"), append = TRUE)
          source(file.path(Sys.getenv("HOME"), ".Rprofile"))
          print(getOption("repos"))
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
